version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: gotuser
      POSTGRES_PASSWORD: gotpassword
      POSTGRES_DB: giftonetime
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
